#include <fstream> 
#include <iostream> 
#include <string>

using namespace std;

/*
Made by Razor118
newline sequence is ASCII LF (0x0A)
struct:
digit/0A/0A/DIR/0A/Revision/0A
*/

int main(int argc, char* argv[])
{
	if(argc != 3)
	{
		cout << "Usage: " << argv[0] << " <svn root> <output>" << endl;
		return -1;
	}

	string entries = argv[1] + string("\\.svn\\entries");

	ifstream file;
	file.open(entries.c_str());

	if(!file)
	{
		cout << "failed to open: " << entries << endl;
		return -2;
	}
	else
	{
		int i = 1;
		int revision = 0;		

		while(!file.eof())
		{
			string buffer;
			getline(file, buffer);

			if(i == 4) revision = atoi(buffer.c_str());

			++i;
		}

		ofstream file(argv[2]);

		file << "//This file was automatically generated by the SVN revision extractor - Faolan Project.\n\n"
			<< "#define SVN_REVISION " << revision;

		file.close();
	}

	return 0;
}